language: node_js

node_js:
  - "4.1"
env:
  - CXX=g++-4.8

sudo: false
cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

script:
  - node scripts/make cover -- lcovonly

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

