init:
  - git config --global core.autocrlf true

clone_depth: 8
os: unstable

environment:
  nodejs_version: "6.2"

platform:
  - x64
  - x86

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm --version
  - npm install --no-optional --no-color --no-progress

test_script:
  - node --version
  - node scripts\make test

build: off
