init:
  - git config --global core.autocrlf true

environment:
  - nodejs_version: 6

platform:
  - x64
  - x86

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - npm install --no-optional --no-color --no-progress

test_script:
  - npm test

version: '{build}'
build: off
